export const GET_CART_ITEMS_REQUEST="GET_CART_ITEMS_REQUEST";
export const GET_CART_ITEMS_SUCCESS="GET_CART_ITEMS_SUCCESS";


export const ADD_CART_ITEMS_REQUEST="ADD_CART_ITEMS_REQUEST";
export const ADD_CART_ITEMS_SUCCESS="ADD_CART_ITEMS_SUCCESS";

export const DELETE_CART_ITEMS_REQUEST="DELETE_CART_ITEMS_REQUEST";
export const DELETE_CART_ITEMS_SUCCESS="DELETE_CART_ITEMS_SUCCESS";

export const UPDATE_QUANTITY_CART_REQUEST="UPDATE_QUANTITY_CART_REQUEST";
export const UPDATE_QUANTITY_CART_SUCCESS="UPDATE_QUANTITY_CART_SUCCESS";