export const CATE_ADD_REQUEST = 'CATE_ADD_REQUEST'
export const CATE_ADD_SUCCESS = 'CATE_ADD_SUCCESS'

export const CATE_GET_REQUEST = 'CATE_GET_REQUEST'
export const CATE_GET_SUCCESS = 'CATE_GET_SUCCESS'


export const CATE_DELETE_REQUEST = "CATE_DELETE_REQUEST";
export const CATE_DELETE_SUCCESS = "CATE_DELETE_SUCCESS";

export const CATE_SUBMIT_REQUEST = "CATE_SUBMIT_REQUEST";
export const CATE_SUBMIT_SUCCESS = "CATE_SUBMIT_SUCCESS";

export const CATE_GET_EDIT_REQUEST = "CATE_GET_EDIT_REQUEST";
export const CATE_GET_EDIT_SUCCESS = "CATE_GET_EDIT_SUCCESS";


export const CATE_UPDATE_EDIT_REQUEST = "CATE_UPDATE_EDIT_REQUEST";
export const CATE_UPDATE_EDIT_SUCCESS = "CATE_UPDATE_EDIT_SUCCESS";