export const LOGIN_MEMBER_REQUEST="LOGIN_MEMBER_REQUEST";
export const LOGIN_MEMBER_SUCCESS="LOGIN_MEMBER_SUCCESS";

export const LOGOUT_MEMBER="LOGOUT_MEMBER";

export const RIGISTER_MEMBER_REQUEST="REGISTER_MEMBER_REQUEST";