//GET
export const PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST";
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";

// Delete
export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";

//SUBMIT
export const PRODUCT_SUBMIT_REQUEST="PRODUCT_SUBMIT_REQUEST";
export const PRODUCT_SUBMIT_SUCCESS="PRODUCT_SUBMIT_SUCCESS";

//GET PRODUCT ADMIN
export const PRODUCT_GET_ADMIN_REQUEST = "PRODUCT_GET_ADMIN_REQUEST";
export const PRODUCT_GET_ADMIN_SUCCESS = "PRODUCT_GET_ADMIN_SUCCESS";

// GET EDIT PRODUCT DATA
export const PRODUCT_GET_EDIT_DATA_REQUEST = "PRODUCT_GET_EDIT_DATA_REQUEST";
export const PRODUCT_GET_EDIT_DATA_SUCCESS = "PRODUCT_GET_EDIT_DATA_SUCCESS";

// UPDATE PRODUCT DATA
export const PRODUCT_UPDATE_EDIT_DATA_REQUEST = "PRODUCT_UPDATE_EDIT_DATA_REQUEST";
export const PRODUCT_UPDATE_EDIT_DATA_SUCCESS = "PRODUCT_UPDATE_EDIT_DATA_SUCCESS";


